/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include	<stdlib.h>

#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	UartInit(BAUD_9600);
	SwitchInit(SWITCH);

	int count =0;
	char str[20];
		while(1) {
			while(exti0_flag ==  0)
				;
			count++;
			DelayMs(200);
			sprintf(str,"\r\n%d",count);
//			itoa(count,str,20);

			UartPuts(str);

			exti0_flag =  0;

		}


	return 0;
}




