/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "uart.h"
#include "lis3dsh.h"
#include "spi.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	int ret;
	LIS_Data val;
	SystemInit();
	UartInit(BAUD_9600);
	LIS_Init();
	SPI_Init();
	LedInit(LED_GREEN);

	LedInit(LED_RED);
	LedInit(LED_BLUE);

	DelayMs(1000);
	while(1) {
		ret = LIS_DRdy();
		if(ret)
		{
			val = LIS_GetData();

			int th =1000;
			if((val.x>val.y) && (val.x>val.z))
			{
				if(value.x>th) LedOn(LED_RED);
				else LedOff(LED_RED);

			}
			else if((val.x<val.y) && (val.y>val.z))
						{
							if(value.y>th) LedOn(LED_Green);
							else LedOff(LED_Green);

						}
			else if((val.z>val.x) && (val.z>val.x))
						{
							if(value.z>th) LedOn(LED_Blue);
							else LedOff(LED_Blue);

						}
			DelayMs(1000);
		}
	}
	return 0;
}







